SELECT * FROM LIVROS
WHERE CATEGORIA = "BIOGRAFIA";


SELECT * FROM LIVROS
WHERE CATEGORIA = "ROMANCE" AND PREÇO < 48;


SELECT * FROM LIVROS
WHERE CATEGORIA = "POESIA" AND NOT (AUTORIA = "Luíz Vaz de Camóes" OR AUTORIA = "Gabriel Pedrosa");