SELECT VENDAS.ID_VENDEDOR, VENDEDORES.NOME_VENDEDOR, sum(VENDAS.QTD_VENDIDA) 
FROM VENDAS, VENDEDORES 
WHERE VENDAS.ID_VENDEDOR = VENDEDORES.ID_VENDEDOR
GROUP BY VENDAS.ID_VENDEDOR; 

# usando o inner join

SELECT VENDAS.ID_VENDEDOR,
 VENDEDORES.NOME_VENDEDOR, 
 sum(VENDAS.QTD_VENDIDA) 
FROM VENDAS INNER JOIN VENDEDORES 
ON VENDAS.ID_VENDEDOR = VENDEDORES.ID_VENDEDOR
GROUP BY VENDAS.ID_VENDEDOR; 


#LEFT JOIN
SELECT LIVROS.NOME_LIVRO,
VENDAS.QTD_VENDIDA
FROM LIVROS LEFT JOIN VENDAS
ON LIVROS.ID_LIVRO = VENDAS.ID_LIVRO
WHERE VENDAS.QTD_VENDIDA IS NULL;


#RIGHT JOIN

SELECT 
	VENDAS.ID_LIVRO,
	LIVROS.NOME_LIVRO,
	VENDAS.QTD_VENDIDA
FROM LIVROS RIGHT JOIN VENDAS
ON LIVROS.ID_LIVRO = VENDAS.ID_LIVRO;